:connection:
  :adapter: sqlite3
  :database: imageboard.db

  #:adapter: mysql
  #:host: localhost
  #:username: myuser
  #:password: mypass
  #:database: iikoto

# max image filesize in bytes
:max_filesize: 2097152

# thread post reply limit
:reply_limit: 300

# thread image reply limit
:image_limit: 150

# default poster name
:default_name: Anonymous

# Hash length to use for image filenames (the longer the better, technically.)
# Note that this affects the length of links to images on your site.
:url_hash_size: 32
